version: "3"
services:
  amq:
    image: rmohr/activemq    
    hostname: 'amq'
    ports:
      - '8160:61616'
      - '8161:8161'

  rabbitmq:
    container_name: dev-rabbitmq
    hostname: rabbit
    image: rabbitmq:3-management
    ports:
     - "5672:5672"
     - "15672:15672"